# Numerical Python(Numpy) - Part 1

In [2]:
# de facto standard (사실상의 표준)
import numpy as np

In [3]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
list(map(lambda x : 3*x, a))

[3, 6, 9]

In [5]:
b = np.array([1, 2, 3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional Array

In [8]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [9]:
type(a)

numpy.ndarray

In [10]:
a.dtype, a.shape

(dtype('float64'), (4,))

## Array shape

In [25]:
# Vector(1차원)
vector = np.array([1, 4, 6, 8])
vector.shape

(4,)

In [18]:
# Matrix(2차원)
matrix = np.array([[1, 2, 3],[4, 5, 6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [22]:
# Tensor(3차원)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)
print(tensor.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [27]:
# elelment의 갯수 (shpae 숫자 다 곱하기)
vector.size, matrix.size, tensor.size      

(4, 6, 24)

In [29]:
a = np.array([1,2,3], dtype=np.float32)     #dtype= 은 뺴도 됨
a

array([1., 2., 3.], dtype=float32)

In [31]:
b = np.array([1,2,3], dtype = np.int16)
b

array([1, 2, 3], dtype=int16)

## reshpae

In [36]:
# reshape
matrix.shape

(2, 3)

In [33]:
matrix.reshape(6, )

array([1, 2, 3, 4, 5, 6])

In [35]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
# -1은 numpy가 알아서 맞춰준다 (단, size가 동일)
matrix.reshape(-1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [41]:
matrix.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
matrix.reshape(3, -1).shape

(3, 2)

In [45]:
tensor.reshape(6, -1).shape

(6, 4)

### flatten

In [47]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [49]:
tensor.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

In [50]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
matrix[0][1]

2

In [53]:
matrix[0, 1]        # numpy에서는 이런거도 가능

2

In [54]:
tensor[1,1,2]

19

### slicing

In [56]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
# 5,6,9,10
b[1:3, 1:3]     

array([[ 5,  6],
       [ 9, 10]])

In [60]:
#5,6,7,9,10,11
b[1:3, 1:]     # 행, 열

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [61]:
# 1,3,9,11
b[0::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [72]:
# X는 앞에 3열, y는 마지막 열
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))