In [62]:
import numpy as np

## 1. 넘파이를 사용하여 사용하여 사용하여 다음과 같은 행렬을 만드시오
<br>10 20 30 40
<br>50 60 70 80

In [2]:
a = np.arange(10, 81, 10).reshape(2, 4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [63]:
np.arange(1,9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 2. 다음 행렬과 같은 행렬이 있다 .
<br> m = np.array([[0, 1, 2, 3, 4]
<br>             [ 5, 6, 7, 8, 9],
<br>             [ 10, 11, 12, 13, 14]])
<br>
<br>1) 이 행렬에서 값 7 을 인덱싱한다.
<br>2) 이 행렬에서 값 14 을 인덱싱한다 .
<br>3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다
<br>4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다
<br>5) 이 행렬에서 배열 [[3, 4], [8, 9]]을 슬라이싱한다

In [15]:
m = np.array([[0, 1, 2, 3, 4], 
              [ 5, 6, 7, 8, 9],
              [ 10, 11, 12, 13, 14]])
print('#1)')
print(m[1,2])
print('#2)')
print(m[-1,-1])
print('#3)')
print(m[1, 1:3])
print('#4)')
print(m[1:, 2])
print('#5)')
print(m[:2, 3:])


#1)
7
#2)
14
#3)
[6 7]
#4)
[ 7 12]
#5)
[[3 4]
 [8 9]]


## 3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 다음의 문제를 푸시오.
<br>1) 이 배열에서 3의 배수를 찾아라 .
<br>2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라 .
<br>3) 이 배열에서 3으로 나누면 나누어지고 나누어지고 4로 나누면 나누면 1이 남는 수를 찾아라 .

In [22]:
m = m.reshape(-1,)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
m[m%3 == 0]

array([ 0,  3,  6,  9, 12])

In [26]:
m[m % 4 == 1]

array([ 1,  5,  9, 13])

In [32]:
m[np.logical_and(m % 3 == 0, m %4 ==1)]

array([9])

4. 값을 직접 입력하지 말고 우측의 행렬을 행렬을 만드시오 .

In [34]:
(np.eye(5, 5) * 2) + np.eye(5, 5, 1) + np.eye(5, 5, -1) *3

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

## 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.

<br>
<br>1) 전체의 최댓값
<br>2) 각 행의 합
<br>3) 각 행의 최댓값
<br>4) 각 열의 평균
<br>5) 각 열의 최솟값


In [73]:
np.random.seed(2001)
no5 = np.random.uniform(0, 10, 30).reshape(5, 6).round(4)
no5

array([[1.6713, 0.81  , 9.6023, 9.3845, 6.2086, 4.256 ],
       [6.8978, 2.4203, 3.666 , 1.4195, 2.1019, 9.0794],
       [6.4405, 2.0727, 4.3597, 9.5636, 6.9779, 5.2989],
       [5.811 , 3.3954, 8.175 , 0.816 , 6.5422, 6.4452],
       [9.0425, 8.2497, 2.6373, 4.3155, 4.9897, 1.503 ]])

In [76]:
np.max(no5)

9.6023

In [77]:
no5.sum(axis =1)

array([31.9327, 25.5849, 34.7133, 31.1848, 30.7377])

In [78]:
np.max(no5, axis = 1)

array([9.6023, 9.0794, 9.5636, 8.175 , 9.0425])

In [80]:
no5.mean(axis = 0)

array([5.97262, 3.38962, 5.68806, 5.09982, 5.36406, 5.3165 ])

In [79]:
np.min(no5, axis = 0)        # 각 인덱스 값이 얼마인지

array([1.6713, 0.81  , 2.6373, 0.816 , 2.1019, 1.503 ])

## 6. Sorting

In [85]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [86]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [87]:
# 내림차순
s[::-1]

array([2, 1, 3, 0])

In [89]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [94]:
# 한줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

## 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오

In [96]:
np.random.seed(2021)
np.random.randint(1, 7, 100).mean()

3.7

## 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [61]:
a = np.random.normal(0, 1, size = 250)
a

array([ 0.30233893,  1.13307083,  0.00391642,  0.7729168 , -0.26824874,
        1.01272275,  0.49559786,  2.52433951, -1.40168121,  0.71438567,
        0.30288553, -0.28528113, -0.9950498 , -0.67212224, -1.01823256,
        1.20947573, -1.48198446,  1.41105659, -0.26504951, -1.37846678,
        0.53414812, -1.37141478,  0.88701002,  1.05747135, -0.61132789,
       -1.30343259,  1.66555362,  0.66975774, -0.48375854,  0.89526019,
        1.14847013, -0.04880591,  0.03739045,  1.74180418, -0.17748451,
        1.60455668, -0.25419418,  0.83880612,  0.82696369,  1.00017418,
       -0.56408527,  0.8136371 , -0.43365426,  0.31208839, -1.01169615,
        0.03083503,  1.10489223,  0.73852096,  0.0272985 , -0.11996506,
        0.20062323, -0.84666913,  0.2450395 , -0.60242622, -1.48058389,
       -0.76908094, -0.05685946,  0.6385146 ,  1.56880722, -0.00448084,
       -1.76297694, -0.83945691,  0.58859862, -0.43612297,  0.34703122,
       -0.17057634,  1.31724341,  1.77273826,  2.08701767, -2.03